project:
  type: website

website:
  title: "Alexandra McSween"
  description: "Personal site for Alexandra McSween"
  image: avatar.jpg
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: My Projects
    open-graph: true

format:
  html:
    theme: 
      light: minty
      dark: darkly
    css: styles.css
    toc: true